spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jyj10241103*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false